fitting_har_method: "ols" # options: "ols", "wls"
har_train_window_size: 1000
har_prediction_window_size: 8
RV_transformation: "log" # options: "sqrt", "log"
jump_test_alpha: 0.01
hawkes_window_size: 1000
hawkes_step_size: 8

lstm_train_window_size: 1200
lstm_prediction_window_size: 8
lstm_val_ratio: 0.25
lstm_lookback_days: 30

lstm_hidden_size: 64
lstm_output_activation: "linear" # options: "linear", "relu", "tanh", "gelu", "softplus"
lstm_criterion: "mse" # options: "mse", "mae", "hmse", "hmae"
lstm_optimizer: "adam" # options: "adam", "adamw"
lstm_lr: 0.001
lstm_epochs: 500
lstm_batch_size: 64
lstm_patience: 30
lstm_min_delta: 0.0
lstm_device: "cuda" # options: "cuda", "cpu"
